Repository melt-ui/melt-ui, pull requests merged in 2023-07, with the labels that each got.

#138 Refactor: builder wrapper
  README.md
  src/lib/builders/accordion/index.ts
  src/lib/builders/avatar/index.ts
  src/lib/builders/checkbox/index.ts
  src/lib/builders/collapsible/index.ts
  src/lib/builders/collapsible/tests/CollapsibleTest.svelte
  src/lib/builders/context-menu/index.ts
  src/lib/builders/dropdown-menu/index.ts
  src/lib/builders/menu/index.ts
  src/lib/builders/menubar/index.ts
  src/lib/builders/select/index.ts
  src/lib/builders/tabs/index.ts
  src/lib/internal/helpers/builder.ts
  src/lib/internal/helpers/rovingFocus.ts
  src/routes/(components)/tabs/list.svelte
  src/routes/docs/builders/accordion/(examples)/(preview)/preview.svelte
  src/routes/docs/builders/checkbox/(examples)/(preview)/preview.svelte
  src/routes/docs/builders/collapsible/(examples)/(preview)/preview.svelte
  src/routes/docs/builders/context-menu/(examples)/(preview)/preview.svelte
  src/routes/docs/builders/dropdown-menu/(examples)/(preview)/preview.svelte
  src/routes/docs/builders/label/(examples)/(preview)/preview.svelte
  src/routes/docs/builders/menubar/(examples)/(preview)/preview.svelte
  src/routes/docs/builders/tabs/(examples)/(preview)/preview.svelte
Labels: tech debt

#174 Several fixes
  .changeset/mighty-goats-hear.md
  .changeset/pretty-planes-smell.md
  .changeset/rich-carpets-compete.md
  src/lib/builders/combobox/create.ts
  src/lib/builders/menu/create.ts
  src/lib/builders/select/create.ts
  src/lib/builders/slider/create.ts
  src/lib/builders/tabs/create.ts
Labels: bug

#228 [New Builder] Toast
  .changeset/mighty-planes-yawn.md
  src/docs/content/builders/toast.md
  src/docs/data/builders/index.ts
  src/docs/data/builders/toast.ts
  src/docs/previews/toast/main/tailwind.svelte
  src/lib/builders/index.ts
  src/lib/builders/toast/create.ts
  src/lib/builders/toast/index.ts
  src/lib/builders/toast/types.ts
Labels: enhancement
